import "./globals.css";

export const metadata = {
  title: "리액트 테스트",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
